artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/dataingestion
  data_url: "https://github.com/Abhikkumar619/dataset/commit/72ddf3db8fe626e1ec25a84cf67f57a2160f2bdf"
  data_zip_path: artifacts/dataingestion/bone_fracture.zip
  unzip_dir: artifacts/dataingestion


  
